using System.Security.Cryptography;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Npgsql;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using ReportService.Application.Common.Interfaces;
using ReportService.Domain.Entities;

namespace ReportService.Infrastructure.Reports;

/// <summary>
/// GAP-043: Chat thread PDF export generator.
/// Reads messages from chat.messages (cross-schema, same DB, read-only via raw Npgsql).
/// Renders as a formatted PDF using QuestPDF (fonts CI-verified in Wave 6).
///
/// Job parameters: OrgId + FinancialYear (used as thread ID string for now;
/// the endpoint encodes the thread ID as the FinancialYear field to avoid schema changes).
/// Returns a PDF with sender role, timestamp, and body for each message.
/// </summary>
public sealed class ChatThreadPdfGenerator(
    IReportStorageService storage,
    IConfiguration configuration,
    ILogger<ChatThreadPdfGenerator> logger) : IReportGenerator
{
    /// <inheritdoc />
    public bool Supports(ReportType reportType, ReportFormat format)
        => reportType == ReportType.ChatThreadPdf;

    /// <inheritdoc />
    public async Task<ReportGenerationResult> GenerateAsync(ReportJob job, CancellationToken ct)
    {
        // ThreadId is encoded in FinancialYear field (string UUID)
        if (!Guid.TryParse(job.FinancialYear, out var threadId))
        {
            logger.LogError("ChatThreadPdfGenerator: Invalid thread ID in FinancialYear field: {Value}", job.FinancialYear);
            return new ReportGenerationResult("", "", 0);
        }

        var messages = await FetchThreadMessagesAsync(threadId, job.OrgId, ct);

        var doc = Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(30);

                page.Header().Element(c =>
                    SnapAccountDocumentStyles.RenderHeader(c,
                        "Chat Thread Export",
                        $"Thread {threadId}",
                        DateTime.UtcNow.ToString("dd MMM yyyy HH:mm") + " UTC"));

                page.Content().Padding(10).Column(col =>
                {
                    col.Spacing(8);

                    if (messages.Count == 0)
                    {
                        col.Item().Text("No messages found in this thread.")
                            .FontSize(11).FontColor(Colors.Grey.Medium);
                        return;
                    }

                    foreach (var msg in messages)
                    {
                        col.Item().Border(0.5f).BorderColor(Colors.Grey.Lighten2)
                            .Padding(8).Column(msgCol =>
                            {
                                // Header row: sender role + timestamp
                                msgCol.Item().Row(row =>
                                {
                                    row.RelativeItem().Text(
                                        $"[{msg.SenderRole}]" +
                                        (msg.SenderUserId.HasValue ? $" User {msg.SenderUserId.Value.ToString("N")[..8]}" : " [anonymized]"))
                                        .FontSize(9).Bold().FontColor(Colors.Grey.Darken2);

                                    row.ConstantItem(160).AlignRight().Text(
                                        msg.CreatedAt.ToString("dd MMM yyyy HH:mm") + " UTC")
                                        .FontSize(9).FontColor(Colors.Grey.Medium);
                                });

                                // Message body
                                msgCol.Item().PaddingTop(4).Text(msg.Body)
                                    .FontSize(10);
                            });
                    }
                });

                page.Footer().AlignCenter().Text(text =>
                {
                    text.Span("Generated by SnapAccount | Confidential | Page ").FontSize(8);
                    text.CurrentPageNumber().FontSize(8);
                    text.Span(" of ").FontSize(8);
                    text.TotalPages().FontSize(8);
                });
            });
        });

        var pdfBytes = doc.GeneratePdf();
        var sha256Hex = Convert.ToHexString(SHA256.HashData(pdfBytes)).ToLowerInvariant();

        var bucketName = Environment.GetEnvironmentVariable("GCS_REPORTS_BUCKET")
            ?? configuration["GCS:ReportsBucket"]
            ?? "snapaccount-reports-dev";

        var objectName = $"reports/{job.OrgId}/chat-threads/{threadId}/{job.Id}.pdf";
        var gcsUri = await storage.UploadAsync(bucketName, objectName, pdfBytes, "application/pdf", ct);

        var pageCount = pdfBytes.Length / 3000 + 1; // Rough estimate
        logger.LogInformation(
            "ChatThreadPdfGenerator: Generated PDF for thread {ThreadId}, {MessageCount} messages",
            threadId, messages.Count);

        return new ReportGenerationResult(gcsUri, sha256Hex, pageCount);
    }

    // ── Cross-schema read ─────────────────────────────────────────────────────

    private string GetConnectionString()
    {
        var dbPassword = configuration["DB_PASSWORD"] ?? "postgresql";
        return (configuration.GetConnectionString("DefaultConnection")
            ?? configuration.GetConnectionString("snapaccount")
            ?? "Host=localhost;Port=5432;Database=snapaccount;Username=postgres;Password=#{DB_PASSWORD}#")
            .Replace("#{DB_PASSWORD}#", dbPassword);
    }

    private async Task<List<ChatMessageRow>> FetchThreadMessagesAsync(
        Guid threadId, Guid orgId, CancellationToken ct)
    {
        // Verify thread belongs to org before reading (IDOR guard)
        var results = new List<ChatMessageRow>();
        try
        {
            await using var conn = new NpgsqlConnection(GetConnectionString());
            await conn.OpenAsync(ct);

            // First: verify thread ownership
            await using var checkCmd = new NpgsqlCommand("""
                SELECT COUNT(1) FROM chat.threads
                WHERE id = @threadId AND org_id = @orgId AND deleted_at IS NULL
                """, conn);
            checkCmd.Parameters.AddWithValue("threadId", threadId);
            checkCmd.Parameters.AddWithValue("orgId", orgId);
            var count = (long)(await checkCmd.ExecuteScalarAsync(ct) ?? 0L);

            if (count == 0)
            {
                logger.LogWarning(
                    "ChatThreadPdfGenerator: Thread {ThreadId} not found for org {OrgId}. Returning empty PDF.",
                    threadId, orgId);
                return results;
            }

            // Fetch messages ordered by creation time
            await using var msgCmd = new NpgsqlCommand("""
                SELECT sender_user_id, sender_role, body, created_at
                FROM   chat.messages
                WHERE  thread_id = @threadId
                  AND  deleted_at IS NULL
                ORDER  BY created_at ASC
                LIMIT  5000
                """, conn);
            msgCmd.Parameters.AddWithValue("threadId", threadId);

            await using var reader = await msgCmd.ExecuteReaderAsync(ct);
            while (await reader.ReadAsync(ct))
            {
                results.Add(new ChatMessageRow(
                    reader.IsDBNull(0) ? null : reader.GetGuid(0),
                    reader.GetString(1),
                    reader.GetString(2),
                    reader.GetDateTime(3)));
            }
        }
        catch (Exception ex)
        {
            logger.LogWarning(ex,
                "ChatThreadPdfGenerator: Failed to read chat.messages for thread {ThreadId}. Returning empty list.",
                threadId);
        }
        return results;
    }

    private sealed record ChatMessageRow(Guid? SenderUserId, string SenderRole, string Body, DateTime CreatedAt);
}
