// NOTE FOR BACKEND-AGENT (P6-INT-02):
// To enable WebApplicationFactory<Program>, add the following to
// backend/Services/LoanService/LoanService.Api/LoanService.Api.csproj:
//
//   <ItemGroup>
//     <InternalsVisibleTo Include="LoanService.IntegrationTests" />
//   </ItemGroup>
//
// Without this, the implicit Program class generated by top-level statements
// is internal and not accessible to this test project.
// These tests are authored-only and will be gated by CI Docker socket (P6-INT-02).

using FluentAssertions;
using LoanService.Application.Common.Interfaces;
using LoanService.Domain.Entities;
using LoanService.Infrastructure.Persistence;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using Moq;
using System.Net;
using System.Net.Http.Json;
using System.Security.Cryptography;
using System.Text;
using System.Text.Json;
using Testcontainers.PostgreSql;
using Xunit;

namespace LoanService.IntegrationTests;

/// <summary>
/// Integration tests for the Loan Service.
/// Uses Testcontainers (PostgreSQL 17) following the pattern established in
/// AuthService.IntegrationTests and GstService.IntegrationTests.
///
/// Blocked by P6-INT-02: InternalsVisibleTo not yet added to LoanService.Api.csproj.
/// Author status: COMPLETE — pending CI Docker socket and InternalsVisibleTo.
/// </summary>
[Collection("LoanApi")]
public class LoanStateMachineIntegrationTests : IAsyncLifetime
{
    private readonly PostgreSqlContainer _postgres = new PostgreSqlBuilder()
        .WithImage("postgres:17-alpine")
        .WithDatabase("snapaccount_test")
        .WithUsername("postgres")
        .WithPassword("postgres_test")
        .Build();

    private HttpClient _client = null!;
    private WebApplicationFactory<Program> _factory = null!;
    private readonly Mock<ICredentialEncryptionService> _credentialEncryptionMock = new();
    private readonly Mock<ILoanEventPublisher> _eventPublisherMock = new();

    // ──────────────────────────────────────────────────────────────
    // IAsyncLifetime
    // ──────────────────────────────────────────────────────────────

    public async Task InitializeAsync()
    {
        await _postgres.StartAsync();

        // Default mock: return a no-op for webhook secret lookups
        _credentialEncryptionMock
            .Setup(x => x.GetWebhookSecretAsync(It.IsAny<string>(), It.IsAny<CancellationToken>()))
            .ReturnsAsync(Encoding.UTF8.GetBytes("integration-test-webhook-secret-32b!"));

        // Default mock: event publisher silently succeeds (topic + payload signature)
        _eventPublisherMock
            .Setup(x => x.PublishAsync(It.IsAny<string>(), It.IsAny<object>(), It.IsAny<CancellationToken>()))
            .Returns(Task.CompletedTask);

        _factory = new WebApplicationFactory<Program>()
            .WithWebHostBuilder(builder =>
            {
                builder.UseEnvironment("Testing");
                builder.ConfigureServices(services =>
                {
                    // Replace EF Core connection with test container
                    services.RemoveAll<DbContextOptions>();
                    services.RemoveAll<DbContextOptions<LoanServiceDbContext>>();
                    services.AddDbContext<LoanServiceDbContext>(options =>
                        options.UseNpgsql(_postgres.GetConnectionString()));

                    // Replace external service mocks
                    services.RemoveAll<ICredentialEncryptionService>();
                    services.AddSingleton(_credentialEncryptionMock.Object);

                    services.RemoveAll<ILoanEventPublisher>();
                    services.AddSingleton(_eventPublisherMock.Object);
                });
            });

        _client = _factory.CreateClient();

        // Apply EF Core migrations
        using var scope = _factory.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<LoanServiceDbContext>();
        await db.Database.MigrateAsync();
    }

    public async Task DisposeAsync()
    {
        _client.Dispose();
        await _factory.DisposeAsync();
        await _postgres.DisposeAsync();
    }

    // ──────────────────────────────────────────────────────────────
    // Helper: create a test LoanApplication in a given status
    // ──────────────────────────────────────────────────────────────

    private async Task<Guid> SeedLoanApplicationAsync(LoanApplicationStatus status)
    {
        using var scope = _factory.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<LoanServiceDbContext>();

        // Seed a minimal LoanProduct — Id auto-generated by BaseEntity
        var product = new LoanProduct
        {
            BankId = Guid.NewGuid(),
            ProductName = "Test Product",
            MinAmount = 100_000,
            MaxAmount = 10_000_000,
            IsActive = true,
        };
        db.LoanProducts.Add(product);
        await db.SaveChangesAsync();

        var app = new LoanApplication
        {
            OrgId = Guid.NewGuid(),
            UserId = Guid.NewGuid(),
            LoanProductId = product.Id,
            RequestedAmount = 500_000,
            TenureMonths = 24,
            Purpose = "Working capital",
        };

        // Advance to requested status via domain state machine
        if (status >= LoanApplicationStatus.Submitted)
            app.Submit();
        if (status >= LoanApplicationStatus.UnderReview)
            app.BeginReview();
        if (status == LoanApplicationStatus.DocsRequested)
            app.RequestDocuments();
        if (status >= LoanApplicationStatus.Approved && status != LoanApplicationStatus.Rejected)
            app.Approve("BANK-REF-001");
        if (status == LoanApplicationStatus.Rejected)
        {
            // Reject requires UnderReview — ensure we're there first
            if (app.Status == LoanApplicationStatus.Submitted)
                app.BeginReview();
            app.Reject("Risk too high");
        }
        if (status >= LoanApplicationStatus.Disbursed)
            app.RecordDisbursement(500_000m, "UTR-001");
        if (status == LoanApplicationStatus.Closed)
            app.Close();

        db.LoanApplications.Add(app);
        await db.SaveChangesAsync();
        return app.Id;
    }

    // ──────────────────────────────────────────────────────────────
    // State machine: invalid transitions return Conflict (409)
    // ──────────────────────────────────────────────────────────────

    /// <summary>
    /// Attempting to Approve a DRAFT application (which is not in UNDER_REVIEW)
    /// should return HTTP 409 Conflict.
    /// P6-HANDOFF-28: every invalid state transition must return Conflict, not 500.
    /// </summary>
    [Fact(Skip = "P6-INT-02: InternalsVisibleTo not yet configured on LoanService.Api")]
    public async Task ApproveApplication_FromDraftStatus_Returns409Conflict()
    {
        // Arrange: seed a DRAFT application
        var applicationId = await SeedLoanApplicationAsync(LoanApplicationStatus.Draft);

        // Act
        var response = await _client.PostAsJsonAsync(
            $"/loans/applications/{applicationId}/approve",
            new { bankReferenceNo = "BANK-REF-TEST" });

        // Assert
        response.StatusCode.Should().Be(HttpStatusCode.Conflict);
    }

    /// <summary>
    /// Attempting to Reject an application that is DRAFT (not under review)
    /// should return HTTP 409 Conflict.
    /// </summary>
    [Fact(Skip = "P6-INT-02: InternalsVisibleTo not yet configured on LoanService.Api")]
    public async Task RejectApplication_FromDraftStatus_Returns409Conflict()
    {
        // Arrange: seed a DRAFT application
        var applicationId = await SeedLoanApplicationAsync(LoanApplicationStatus.Draft);

        // Act
        var response = await _client.PostAsJsonAsync(
            $"/loans/applications/{applicationId}/reject",
            new { reason = "Not eligible" });

        // Assert
        response.StatusCode.Should().Be(HttpStatusCode.Conflict);
    }

    /// <summary>
    /// Valid transition: SUBMITTED → UNDER_REVIEW should return HTTP 200
    /// and persist the status change.
    /// P6-HANDOFF-28: status_log row must be inserted in the same UoW.
    /// </summary>
    [Fact(Skip = "P6-INT-02: InternalsVisibleTo not yet configured on LoanService.Api")]
    public async Task BeginReview_FromSubmittedStatus_Returns200AndPersistsStatus()
    {
        // Arrange: seed a SUBMITTED application
        var applicationId = await SeedLoanApplicationAsync(LoanApplicationStatus.Submitted);

        // Act
        var response = await _client.PostAsync(
            $"/loans/applications/{applicationId}/begin-review", null);

        // Assert HTTP 200
        response.StatusCode.Should().Be(HttpStatusCode.OK);

        // Assert DB: status persisted as UnderReview
        using var scope = _factory.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<LoanServiceDbContext>();
        var app = await db.LoanApplications.FindAsync(applicationId);
        app.Should().NotBeNull();
        app!.Status.Should().Be(LoanApplicationStatus.UnderReview);
    }

    /// <summary>
    /// Valid transition: UNDER_REVIEW → APPROVED must also insert a status_log row
    /// in the same Unit of Work (P6-HANDOFF-28).
    /// </summary>
    [Fact(Skip = "P6-INT-02: InternalsVisibleTo not yet configured on LoanService.Api")]
    public async Task ApproveApplication_FromUnderReview_PersistsStatusLogRow()
    {
        // Arrange
        var applicationId = await SeedLoanApplicationAsync(LoanApplicationStatus.UnderReview);

        // Act
        var response = await _client.PostAsJsonAsync(
            $"/loans/applications/{applicationId}/approve",
            new { bankReferenceNo = "BANK-REF-INTTEST" });
        response.StatusCode.Should().Be(HttpStatusCode.OK);

        // Assert: at least one ApplicationStatusLog row for this application with toStatus = Approved
        using var scope = _factory.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<LoanServiceDbContext>();
        var logExists = await db.ApplicationStatusLogs
            .AnyAsync(l =>
                l.ApplicationId == applicationId &&
                l.ToStatus == nameof(LoanApplicationStatus.Approved));
        logExists.Should().BeTrue(because: "approving must insert a status_log row in the same UoW");
    }

    // ──────────────────────────────────────────────────────────────
    // IDOR: cross-org application should return NotFound
    // ──────────────────────────────────────────────────────────────

    /// <summary>
    /// A request for a LoanApplication belonging to a different organisation
    /// must return HTTP 404 NotFound, not 403 (avoid oracle attacks).
    /// P6-HANDOFF-29: IDOR check enforced by PermissionBehavior + org-scoped query.
    /// </summary>
    [Fact(Skip = "P6-INT-02: InternalsVisibleTo not yet configured on LoanService.Api")]
    public async Task GetLoanApplication_CrossOrg_Returns404NotFound()
    {
        // Arrange: seed an application belonging to a different org
        var applicationId = await SeedLoanApplicationAsync(LoanApplicationStatus.Submitted);

        // Act: request using a JWT that carries a different orgId
        // In testing mode, FirebaseAuthMiddleware reads X-Test-OrgId header
        var request = new HttpRequestMessage(HttpMethod.Get, $"/loans/applications/{applicationId}");
        request.Headers.Add("X-Test-OrgId", Guid.NewGuid().ToString()); // different org
        var response = await _client.SendAsync(request);

        // Assert
        response.StatusCode.Should().Be(HttpStatusCode.NotFound);
    }

    // ──────────────────────────────────────────────────────────────
    // ConsentRecorded: HMAC signature_hash 32-byte length
    // ──────────────────────────────────────────────────────────────

    /// <summary>
    /// Recording a consent via POST /loans/applications/:id/consents must persist
    /// a Consent row whose signature_hash is exactly 32 bytes (HMAC-SHA256 output).
    /// P6-HANDOFF-26: signature_hash = HMAC-SHA256(userId|appId|version|signedAt, serverKey).
    /// </summary>
    [Fact(Skip = "P6-INT-02: InternalsVisibleTo not yet configured on LoanService.Api")]
    public async Task RecordConsent_ValidPayload_SignatureHashIs32Bytes()
    {
        // Arrange
        var applicationId = await SeedLoanApplicationAsync(LoanApplicationStatus.Submitted);

        var payload = new
        {
            consentType = "CreditBureau",
            consentTextVersion = "v2.1",
        };

        // Act
        var response = await _client.PostAsJsonAsync(
            $"/loans/applications/{applicationId}/consents", payload);
        response.StatusCode.Should().Be(HttpStatusCode.Created);

        // Assert: DB row has exactly 32-byte signature_hash
        using var scope = _factory.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<LoanServiceDbContext>();
        var consent = await db.Consents
            .Where(c => c.ApplicationId == applicationId)
            .OrderByDescending(c => c.CreatedAt)
            .FirstOrDefaultAsync();
        consent.Should().NotBeNull();
        consent!.SignatureHash.Should().HaveCount(32,
            because: "HMAC-SHA256 output is always 32 bytes");
    }

    // ──────────────────────────────────────────────────────────────
    // AccountDeletion: anonymise (NOT hard-delete) consents
    // ──────────────────────────────────────────────────────────────

    /// <summary>
    /// When an account deletion Pub/Sub event is processed, the subscriber must
    /// anonymise consent rows (set anonymized_at, clear userId, userAgent, ipAddress)
    /// but MUST NOT hard-delete them (DPDP 7-year retention).
    /// P6-HANDOFF-26: DB trigger BLOCKS hard-delete on loan.consents.
    /// </summary>
    [Fact(Skip = "P6-INT-02: InternalsVisibleTo not yet configured on LoanService.Api")]
    public async Task AccountDeletionEvent_AnonymisesConsents_DoesNotHardDelete()
    {
        // Arrange: seed a consent row directly in DB
        var applicationId = await SeedLoanApplicationAsync(LoanApplicationStatus.Submitted);
        using var setupScope = _factory.Services.CreateScope();
        var db = setupScope.ServiceProvider.GetRequiredService<LoanServiceDbContext>();

        var userId = Guid.NewGuid();
        var consent = new Consent
        {
            ApplicationId = applicationId,
            ConsentType = ConsentType.CreditBureau,
            ConsentTextVersion = "v2.1",
            SignedAt = DateTime.UtcNow,
            SignatureHash = new byte[32],
            UserId = userId,
            IpAddress = "192.168.1.1",
            UserAgent = "Mozilla/5.0 Test Browser",
        };
        db.Consents.Add(consent);
        await db.SaveChangesAsync();
        var consentId = consent.Id;

        // Act: simulate account deletion event via the test endpoint
        var response = await _client.PostAsJsonAsync(
            "/loans/internal/account-deletion",
            new { userId = userId.ToString() });
        response.StatusCode.Should().BeOneOf(HttpStatusCode.OK, HttpStatusCode.NoContent);

        // Assert: row exists (not hard-deleted) but is anonymised
        using var checkScope = _factory.Services.CreateScope();
        var checkDb = checkScope.ServiceProvider.GetRequiredService<LoanServiceDbContext>();
        var row = await checkDb.Consents
            .IgnoreQueryFilters() // bypass soft-delete global filter
            .FirstOrDefaultAsync(c => c.Id == consentId);

        row.Should().NotBeNull(because: "consents must be retained for 7 years; hard-delete is blocked");
        row!.AnonymizedAt.Should().NotBeNull(because: "anonymization_at must be set on erasure");
        row.UserId.Should().BeNull(because: "DPDP erasure clears userId");
        row.IpAddress.Should().BeNullOrEmpty(because: "DPDP erasure clears ipAddress");
        row.UserAgent.Should().BeNullOrEmpty(because: "DPDP erasure clears userAgent");
    }

    // ──────────────────────────────────────────────────────────────
    // DisbursementWebhook: HMAC verify + idempotency dedupe
    // ──────────────────────────────────────────────────────────────

    /// <summary>
    /// A disbursement webhook with an invalid HMAC signature must be rejected with HTTP 401.
    /// P6-HANDOFF-33: CryptographicOperations.FixedTimeEquals prevents timing attacks.
    /// </summary>
    [Fact(Skip = "P6-INT-02: InternalsVisibleTo not yet configured on LoanService.Api")]
    public async Task DisbursementWebhook_InvalidSignature_Returns401()
    {
        // Arrange: seed a partner bank with a webhook secret ref
        using var scope = _factory.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<LoanServiceDbContext>();

        var bank = new PartnerBank
        {
            Name = "Test Webhook Bank",
            AdapterType = BankAdapterType.Rest,
            IsActive = true,
            WebhookSecretRef = "test-webhook-secret-ref",
        };
        db.PartnerBanks.Add(bank);
        await db.SaveChangesAsync();
        var bankId = bank.Id;

        var payloadBytes = JsonSerializer.SerializeToUtf8Bytes(new
        {
            applicationId = Guid.NewGuid().ToString(),
            amount = 500_000,
            utr = "UTR-WEBHOOK-001"
        });

        var request = new HttpRequestMessage(HttpMethod.Post, $"/loans/webhooks/{bankId}/disbursement")
        {
            Content = new ByteArrayContent(payloadBytes),
        };
        request.Content.Headers.ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue("application/json");
        request.Headers.Add("X-Idempotency-Key", Guid.NewGuid().ToString());
        request.Headers.Add("X-Signature", "invalid-signature-value");

        // Act
        var response = await _client.SendAsync(request);

        // Assert: signature mismatch → 401 Unauthorized
        response.StatusCode.Should().Be(HttpStatusCode.Unauthorized);
    }

    /// <summary>
    /// A duplicate idempotency key on the disbursement webhook must return HTTP 200
    /// (accepted but not reprocessed) — the second call must be a no-op.
    /// P6-HANDOFF-33: dedup via loan.webhook_idempotency_keys with 30-day TTL.
    /// </summary>
    [Fact(Skip = "P6-INT-02: InternalsVisibleTo not yet configured on LoanService.Api")]
    public async Task DisbursementWebhook_DuplicateIdempotencyKey_IsNoOp()
    {
        // Arrange: seed an APPROVED application and partner bank
        var applicationId = await SeedLoanApplicationAsync(LoanApplicationStatus.Approved);

        using var setupScope = _factory.Services.CreateScope();
        var db = setupScope.ServiceProvider.GetRequiredService<LoanServiceDbContext>();

        var bank = new PartnerBank
        {
            Name = "Test Idempotency Bank",
            AdapterType = BankAdapterType.Rest,
            IsActive = true,
            WebhookSecretRef = "test-webhook-secret-ref",
        };
        db.PartnerBanks.Add(bank);
        await db.SaveChangesAsync();
        var bankId = bank.Id;

        var idempotencyKey = "idem-key-" + Guid.NewGuid();
        var secret = Encoding.UTF8.GetBytes("integration-test-webhook-secret-32b!");
        var payloadBytes = JsonSerializer.SerializeToUtf8Bytes(new
        {
            applicationId = applicationId.ToString(),
            amount = 500_000,
            utr = "UTR-DEDUP-001"
        });

        var hmac = HMACSHA256.HashData(secret, payloadBytes);
        var sig = Convert.ToHexString(hmac).ToLowerInvariant();

        async Task<HttpResponseMessage> SendWebhook()
        {
            var req = new HttpRequestMessage(HttpMethod.Post, $"/loans/webhooks/{bankId}/disbursement")
            {
                Content = new ByteArrayContent(payloadBytes),
            };
            req.Content.Headers.ContentType = new System.Net.Http.Headers.MediaTypeHeaderValue("application/json");
            req.Headers.Add("X-Idempotency-Key", idempotencyKey);
            req.Headers.Add("X-Signature", sig);
            return await _client.SendAsync(req);
        }

        // Act: first call should succeed
        var firstResponse = await SendWebhook();
        firstResponse.IsSuccessStatusCode.Should().BeTrue();

        // Act: second call with same idempotency key must also succeed (200) but not reprocess
        var secondResponse = await SendWebhook();
        secondResponse.StatusCode.Should().Be(HttpStatusCode.OK);

        // Assert: application status is Disbursed exactly once
        using var checkScope = _factory.Services.CreateScope();
        var checkDb = checkScope.ServiceProvider.GetRequiredService<LoanServiceDbContext>();
        var updatedApp = await checkDb.LoanApplications.FindAsync(applicationId);
        updatedApp!.Status.Should().Be(LoanApplicationStatus.Disbursed);
    }
}

/// <summary>
/// Marks tests in the LoanApi collection to prevent parallel execution
/// (shared Testcontainers port allocation).
/// </summary>
[CollectionDefinition("LoanApi")]
public class LoanApiCollection : ICollectionFixture<object> { }
