using SnapAccount.Shared.Domain;

namespace LoanService.Domain.Entities;

/// <summary>
/// Records a generated loan application PDF package stored on GCS.
/// Canonical watermark text:
///   "Generated by SnapAccount | {orgName} | {date} | Package ID: {id} | Not a CA certification"
/// Canonical disclaimer:
///   "Prepared by SnapAccount from user-provided data. Not a CA certification.
///    Final lending decision rests with the partner bank."
/// </summary>
public class LoanPdfPackage : BaseAuditableEntity
{
    /// <summary>FK to loan.applications.</summary>
    public Guid ApplicationId { get; init; }

    /// <summary>GCS URI (gs://bucket/loan-packages/{app_id}/{package_id}.pdf).</summary>
    public string GcsUri { get; set; } = string.Empty;

    /// <summary>Number of pages in the generated PDF.</summary>
    public int PagesCount { get; set; }

    /// <summary>SHA-256 hash of the PDF content (32 bytes). Checked by DB constraint.</summary>
    public byte[] Sha256Hash { get; set; } = Array.Empty<byte>();

    /// <summary>UTC timestamp of generation.</summary>
    public DateTime GeneratedAt { get; init; }

    /// <summary>User ID who triggered generation.</summary>
    public Guid GeneratedBy { get; init; }

    /// <summary>Watermark text embedded on every PDF page.</summary>
    public string WatermarkText { get; set; } = string.Empty;

    /// <summary>Whether this is the latest package for the application.</summary>
    public bool IsCurrent { get; set; } = true;
}
