namespace LoanService.Application.Common.Interfaces;

/// <summary>
/// Generates the composite loan application PDF package.
/// Implemented in ReportService.Infrastructure using QuestPDF.
/// </summary>
public interface ILoanPdfGenerator
{
    /// <summary>
    /// Generates a loan package PDF containing:
    /// last 12 GSTR-3B + last FY P&L + Balance Sheet + bank summary + KYC documents.
    /// Watermark on every page: "Generated by SnapAccount | {orgName} | {date} | Package ID: {id} | Not a CA certification"
    /// Footer disclaimer on every page: canonical legal text.
    /// </summary>
    /// <param name="applicationId">The loan application ID (becomes Package ID in watermark).</param>
    /// <param name="orgId">Organisation ID for data retrieval.</param>
    /// <param name="orgName">Organisation display name for watermark.</param>
    /// <param name="ct">Cancellation token.</param>
    /// <returns>Tuple of (PDF bytes, SHA-256 hash of bytes, page count).</returns>
    Task<(byte[] PdfBytes, byte[] Sha256Hash, int PageCount)> GenerateAsync(
        Guid applicationId,
        Guid orgId,
        string orgName,
        CancellationToken ct);
}
