using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace ReportService.Infrastructure.Reports;

/// <summary>
/// Shared QuestPDF document styles and branding constants for SnapAccount reports.
/// Disclaimer footer and watermark text per Phase 6C canonical copy.
/// </summary>
internal static class SnapAccountDocumentStyles
{
    /// <summary>
    /// SEC-049: Generic watermark for non-loan reports that do not carry a package identifier.
    /// Loan Package PDFs must use <see cref="LoanPackageWatermark"/> instead.
    /// </summary>
    internal const string WatermarkText =
        "Generated by SnapAccount | Not a CA Certification | For Lending Purposes Only";

    /// <summary>
    /// SEC-049: Canonical loan-package watermark per P6-HANDOFF specification.
    /// Required format: "Generated by SnapAccount | {orgName} | {date} | Package ID: {id} | Not a CA certification"
    /// All four dynamic fields are required for forensic traceability of printed PDFs.
    /// </summary>
    /// <param name="orgName">Organisation display name.</param>
    /// <param name="generatedAt">UTC timestamp when the document was generated.</param>
    /// <param name="packageId">LoanPdfPackage UUID (GCS object primary key).</param>
    internal static string LoanPackageWatermark(string orgName, DateTime generatedAt, Guid packageId) =>
        $"Generated by SnapAccount | {orgName} | {generatedAt:dd MMM yyyy} | Package ID: {packageId} | Not a CA certification";

    internal const string DisclaimerFooter =
        "Prepared by SnapAccount from user-provided data. This is not a CA certification. " +
        "Final lending decision rests with the partner bank. " +
        "Document retention per DPDP Act 2023 (7 years minimum).";

    internal const string PrimaryColor = "#1A56DB";   // SnapAccount blue
    internal const string SecondaryColor = "#6B7280"; // Gray
    internal const string WarningColor = "#D97706";   // Amber
    internal const float HeaderFontSize = 18f;
    internal const float SubHeaderFontSize = 12f;
    internal const float BodyFontSize = 9f;
    internal const float FooterFontSize = 7f;

    /// <summary>Applies the standard SnapAccount header to a container.</summary>
    internal static void RenderHeader(IContainer container, string reportTitle, string orgName, string? period)
    {
        container.Padding(20).Column(col =>
        {
            col.Item().Row(row =>
            {
                row.RelativeItem().Text("SnapAccount")
                    .FontSize(HeaderFontSize).Bold().FontColor(PrimaryColor);
                row.ConstantItem(200).AlignRight().Text($"Generated: {DateTime.UtcNow:dd MMM yyyy}")
                    .FontSize(BodyFontSize).FontColor(SecondaryColor);
            });

            col.Item().Text(reportTitle)
                .FontSize(SubHeaderFontSize).Bold();

            col.Item().Row(row =>
            {
                row.RelativeItem().Text($"Organisation: {orgName}")
                    .FontSize(BodyFontSize).FontColor(SecondaryColor);
                if (!string.IsNullOrEmpty(period))
                    row.RelativeItem().AlignRight().Text($"Period: {period}")
                        .FontSize(BodyFontSize).FontColor(SecondaryColor);
            });

            col.Item().PaddingTop(5).LineHorizontal(1).LineColor(PrimaryColor);
        });
    }

    /// <summary>Applies the standard disclaimer footer to a container.</summary>
    internal static void RenderFooter(IContainer container, int currentPage, int totalPages)
    {
        container.Padding(10).Column(col =>
        {
            col.Item().LineHorizontal(1).LineColor(SecondaryColor);
            col.Item().PaddingTop(4).Row(row =>
            {
                row.RelativeItem().Text(DisclaimerFooter)
                    .FontSize(FooterFontSize).FontColor(SecondaryColor).Italic();
                row.ConstantItem(60).AlignRight()
                    .Text($"Page {currentPage} of {totalPages}")
                    .FontSize(FooterFontSize).FontColor(SecondaryColor);
            });
        });
    }

    /// <summary>Renders a simple data table with headers and rows.</summary>
    internal static void RenderTable(
        IContainer container,
        IReadOnlyList<string> headers,
        IReadOnlyList<IReadOnlyList<string>> rows)
    {
        container.Table(table =>
        {
            table.ColumnsDefinition(cols =>
            {
                foreach (var _ in headers)
                    cols.RelativeColumn();
            });

            // Header row
            foreach (var header in headers)
            {
                table.Header(h => h.Cell().Background(PrimaryColor).Padding(4)
                    .Text(header).FontSize(BodyFontSize).Bold().FontColor(Colors.White));
            }

            // Data rows
            var isEven = false;
            foreach (var row in rows)
            {
                var bg = isEven ? Colors.Grey.Lighten4 : Colors.White;
                foreach (var cell in row)
                {
                    table.Cell().Background(bg).Padding(3)
                        .Text(cell).FontSize(BodyFontSize);
                }
                isEven = !isEven;
            }
        });
    }
}
