// NOTE FOR BACKEND-AGENT (P6-INT-02):
// To enable WebApplicationFactory<Program>, add the following to
// backend/Services/ItrService/ItrService.Api/ItrService.Api.csproj:
//
//   <ItemGroup>
//     <InternalsVisibleTo Include="ItrService.IntegrationTests" />
//   </ItemGroup>
//
// Without this, the implicit Program class generated by top-level statements
// is internal and not accessible to this test project.
// These tests are authored-only and will be gated by CI Docker socket (P6-INT-02).

using FluentAssertions;
using ItrService.Domain.Entities;
using ItrService.Infrastructure.Persistence;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using System.Net;
using System.Net.Http.Json;
using System.Text.Json;
using Testcontainers.PostgreSql;
using Xunit;

namespace ItrService.IntegrationTests;

/// <summary>
/// Shared TestcontainerFixture: one Postgres container per test collection.
/// Re-using the single-container pattern from AuthService.IntegrationTests.
/// </summary>
[Collection("ItrApi")]
public class TaxComputationIntegrationTests : IAsyncLifetime
{
    private readonly PostgreSqlContainer _postgres = new PostgreSqlBuilder()
        .WithImage("postgres:17-alpine")
        .WithDatabase("snapaccount_test")
        .WithUsername("postgres")
        .WithPassword("postgres_test")
        .Build();

    private HttpClient _client = null!;
    private WebApplicationFactory<Program> _factory = null!;

    // ──────────────────────────────────────────────────────────────
    // IAsyncLifetime
    // ──────────────────────────────────────────────────────────────

    public async Task InitializeAsync()
    {
        await _postgres.StartAsync();

        _factory = new WebApplicationFactory<Program>()
            .WithWebHostBuilder(builder =>
            {
                builder.UseEnvironment("Testing");
                builder.ConfigureServices(services =>
                {
                    // Replace connection string with the Testcontainers instance
                    services.RemoveAll<DbContextOptions>();
                    services.RemoveAll<DbContextOptions<ItrServiceDbContext>>();

                    services.AddDbContext<ItrServiceDbContext>(options =>
                        options.UseNpgsql(_postgres.GetConnectionString()));
                });
            });

        _client = _factory.CreateClient();

        // Apply EF Core migrations
        using var scope = _factory.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<ItrServiceDbContext>();
        await db.Database.MigrateAsync();

        // Seed tax slabs for AY2025-26 OLD + NEW regimes
        // P6-HANDOFF-18: never hardcode — these are the minimum required seed rows
        await SeedTaxSlabsAsync(db);
    }

    public async Task DisposeAsync()
    {
        _client.Dispose();
        await _factory.DisposeAsync();
        await _postgres.DisposeAsync();
    }

    // ──────────────────────────────────────────────────────────────
    // Tax Slab Seeder (mirrors the golden file in backend tests)
    // ──────────────────────────────────────────────────────────────

    /// <summary>
    /// Seeds the minimum tax slab versions for AY2025-26 (OLD and NEW regimes)
    /// so that integration tests are self-contained and repeatable.
    ///
    /// Slab values match the golden-file tests already shipped in backend
    /// (TaxComputationEngineTests.cs, AY2025-26 × OLD/NEW).
    /// </summary>
    private static async Task SeedTaxSlabsAsync(ItrServiceDbContext db)
    {
        // NEW regime slabs (FY 2025-26)
        const string newSlabs = """
            [
              {"from_income": 0,      "to_income": 300000,  "rate_pct": 0},
              {"from_income": 300000, "to_income": 700000,  "rate_pct": 5},
              {"from_income": 700000, "to_income": 1000000, "rate_pct": 10},
              {"from_income": 1000000,"to_income": 1200000, "rate_pct": 15},
              {"from_income": 1200000,"to_income": 1500000, "rate_pct": 20},
              {"from_income": 1500000,"to_income": null,    "rate_pct": 30}
            ]
            """;

        // OLD regime slabs (FY 2025-26)
        const string oldSlabs = """
            [
              {"from_income": 0,      "to_income": 250000,  "rate_pct": 0},
              {"from_income": 250000, "to_income": 500000,  "rate_pct": 5},
              {"from_income": 500000, "to_income": 1000000, "rate_pct": 20},
              {"from_income": 1000000,"to_income": null,    "rate_pct": 30}
            ]
            """;

        // Use raw SQL to insert seed rows directly (avoids EF private-setter issue on seed entities)
        await db.Database.ExecuteSqlRawAsync("""
            INSERT INTO itr.tax_slab_versions
              (id, assessment_year, regime, slabs_json, standard_deduction,
               rebate87a_income_limit, rebate87a_max_amount, cess_rate_pct,
               effective_from, effective_until, created_at, updated_at)
            VALUES
              (gen_random_uuid(), 'AY2025-26', 'NEW', {0}::jsonb, 75000,
               700000, 25000, 4, '2025-04-01', NULL, now(), now()),
              (gen_random_uuid(), 'AY2025-26', 'OLD', {1}::jsonb, 50000,
               500000, 12500, 4, '2025-04-01', NULL, now(), now())
            ON CONFLICT DO NOTHING
            """,
            newSlabs.Replace("'", "''"),
            oldSlabs.Replace("'", "''"));
    }

    // ──────────────────────────────────────────────────────────────
    // Tax Computation — reads versioned slabs (P6-HANDOFF-18)
    // ──────────────────────────────────────────────────────────────

    /// <summary>
    /// Happy path: POST /itr/filings/{filingId}/compute-tax with salary income
    /// and NEW regime should return a ComputationResult that reads slabs from DB.
    /// Verifies that the TaxComputationEngine reads itr.tax_slab_versions
    /// (P6-HANDOFF-18: NEVER hardcode slab values).
    /// </summary>
    [Fact(Skip = "P6-INT-02: InternalsVisibleTo not yet configured on ItrService.Api")]
    public async Task ComputeTax_NewRegime_AY2025_26_ReadsVersionedSlabs()
    {
        // Arrange: create an assessee and a filing first
        var assesseeId = await CreateAssesseeAsync();
        var filingId = await CreateFilingAsync(assesseeId, "AY2025-26", "NEW");

        var request = new
        {
            salaryIncome = 600000,
            housePropertyIncome = 0,
            businessIncome = 0,
            capitalGains = 0,
            otherIncome = 0,
            section80C = 0,
            section80D = 0,
            section80E = 0,
            otherDeductions = 0,
            advanceTaxPaid = 0,
            tdsPaid = 42000,
        };

        // Act
        var response = await _client.PostAsJsonAsync($"/itr/filings/{filingId}/compute-tax", request);

        // Assert
        response.StatusCode.Should().Be(HttpStatusCode.OK);
        var body = await response.Content.ReadFromJsonAsync<JsonElement>();

        // The slab version ID must be non-empty (proves it read from DB, not hardcoded)
        body.TryGetProperty("taxSlabVersionId", out var slabVersionId).Should().BeTrue();
        slabVersionId.GetString().Should().NotBeNullOrEmpty();

        // Standard deduction for NEW regime AY2025-26 is ₹75,000
        body.TryGetProperty("standardDeduction", out var stdDed).Should().BeTrue();
        stdDed.GetDecimal().Should().Be(75_000m);

        // Gross total income = salary only (₹6L)
        body.TryGetProperty("grossTotalIncome", out var gti).Should().BeTrue();
        gti.GetDecimal().Should().Be(600_000m);

        // Refund = TDS paid (₹42K) minus net tax
        body.TryGetProperty("payableOrRefund", out var outcome).Should().BeTrue();
        outcome.GetDecimal().Should().BeLessThan(0m); // Refund expected for ₹6L salary

        // Computation hash must be populated (SEC-020 audit invariant)
        body.TryGetProperty("computationHash", out var hash).Should().BeTrue();
        hash.GetString().Should().HaveLength(64); // SHA-256 hex = 64 chars
    }

    /// <summary>
    /// Regime comparison: POST /itr/filings/{filingId}/compare-regimes
    /// should return both OLD and NEW results + a recommendation.
    /// Verifies that the regime comparison reads both slab versions.
    /// </summary>
    [Fact(Skip = "P6-INT-02: InternalsVisibleTo not yet configured on ItrService.Api")]
    public async Task CompareRegimes_AY2025_26_ReturnsBothResultsWithRecommendation()
    {
        // Arrange
        var assesseeId = await CreateAssesseeAsync();
        var filingId = await CreateFilingAsync(assesseeId, "AY2025-26", "NEW");

        var request = new
        {
            salaryIncome = 700000,
            section80C = 150000, // Deductions only relevant for OLD regime
            section80D = 25000,
            tdsPaid = 0,
        };

        // Act
        var response = await _client.PostAsJsonAsync($"/itr/filings/{filingId}/compare-regimes", request);

        // Assert
        response.StatusCode.Should().Be(HttpStatusCode.OK);
        var body = await response.Content.ReadFromJsonAsync<JsonElement>();

        body.TryGetProperty("old", out var oldResult).Should().BeTrue();
        body.TryGetProperty("new", out var newResult).Should().BeTrue();
        body.TryGetProperty("recommendedRegime", out var recommended).Should().BeTrue();
        body.TryGetProperty("taxSaving", out var saving).Should().BeTrue();

        recommended.GetString().Should().BeOneOf("OLD", "NEW");
        saving.GetDecimal().Should().BeGreaterOrEqualTo(0m);
    }

    // ──────────────────────────────────────────────────────────────
    // Filing State Machine: DRAFT → UNDER_CA_REVIEW → USER_APPROVED
    //                       → FILED → E_VERIFIED
    // ──────────────────────────────────────────────────────────────

    /// <summary>
    /// State machine happy path: a filing progresses through the full
    /// lifecycle from DRAFT to E_VERIFIED.
    /// P6-HANDOFF-18: computation must be pinned before submission.
    /// </summary>
    [Fact(Skip = "P6-INT-02: InternalsVisibleTo not yet configured on ItrService.Api")]
    public async Task FilingStateMachine_DraftToEVerified_FullLifecycle()
    {
        // Step 1: Create assessee + DRAFT filing
        var assesseeId = await CreateAssesseeAsync();
        var filingId = await CreateFilingAsync(assesseeId, "AY2025-26", "NEW");

        // Step 2: Compute tax to pin computation (required before submission)
        var computeRequest = new { salaryIncome = 600000, tdsPaid = 42000 };
        var computeResp = await _client.PostAsJsonAsync($"/itr/filings/{filingId}/compute-tax", computeRequest);
        computeResp.StatusCode.Should().Be(HttpStatusCode.OK);

        // Step 3: Submit for CA review (DRAFT → UNDER_CA_REVIEW)
        var submitResp = await _client.PostAsync($"/itr/filings/{filingId}/submit-for-review", null);
        submitResp.StatusCode.Should().Be(HttpStatusCode.OK);

        var filingAfterSubmit = await GetFilingAsync(filingId);
        filingAfterSubmit.GetProperty("status").GetString().Should().Be("UNDER_CA_REVIEW");

        // Step 4: CA approves (UNDER_CA_REVIEW → USER_APPROVED)
        var approveRequest = new { caUserId = Guid.NewGuid().ToString() };
        var approveResp = await _client.PostAsJsonAsync($"/itr/filings/{filingId}/ca-approve", approveRequest);
        approveResp.StatusCode.Should().Be(HttpStatusCode.OK);

        var filingAfterApprove = await GetFilingAsync(filingId);
        filingAfterApprove.GetProperty("status").GetString().Should().Be("USER_APPROVED");

        // Step 5: Mark as filed (USER_APPROVED → FILED)
        var fileRequest = new { acknowledgementNumber = "ACK20260425001" };
        var fileResp = await _client.PostAsJsonAsync($"/itr/filings/{filingId}/mark-filed", fileRequest);
        fileResp.StatusCode.Should().Be(HttpStatusCode.OK);

        var filingAfterFiled = await GetFilingAsync(filingId);
        filingAfterFiled.GetProperty("status").GetString().Should().Be("FILED");

        // Step 6: Mark as e-verified (FILED → E_VERIFIED)
        var eVerifyRequest = new { method = "AADHAAR_OTP" };
        var eVerifyResp = await _client.PostAsJsonAsync($"/itr/filings/{filingId}/mark-e-verified", eVerifyRequest);
        eVerifyResp.StatusCode.Should().Be(HttpStatusCode.OK);

        var filingAfterEVerify = await GetFilingAsync(filingId);
        filingAfterEVerify.GetProperty("status").GetString().Should().Be("E_VERIFIED");
    }

    /// <summary>
    /// State machine error path: submitting a DRAFT with no pinned computation
    /// should return 409 Conflict (Filing.NoComputation).
    /// </summary>
    [Fact(Skip = "P6-INT-02: InternalsVisibleTo not yet configured on ItrService.Api")]
    public async Task FilingStateMachine_SubmitWithoutComputation_Returns409()
    {
        // Arrange: filing with no computation pinned
        var assesseeId = await CreateAssesseeAsync();
        var filingId = await CreateFilingAsync(assesseeId, "AY2025-26", "NEW");

        // Act: try to submit without running compute-tax first
        var response = await _client.PostAsync($"/itr/filings/{filingId}/submit-for-review", null);

        // Assert: 409 Conflict — computation not pinned
        response.StatusCode.Should().Be(HttpStatusCode.Conflict);
    }

    /// <summary>
    /// State machine error path: CA cannot approve a filing that is not in
    /// UNDER_CA_REVIEW status (e.g., DRAFT). Should return 409 Conflict.
    /// </summary>
    [Fact(Skip = "P6-INT-02: InternalsVisibleTo not yet configured on ItrService.Api")]
    public async Task FilingStateMachine_CaApproveFromDraft_Returns409()
    {
        var assesseeId = await CreateAssesseeAsync();
        var filingId = await CreateFilingAsync(assesseeId, "AY2025-26", "NEW");

        var approveRequest = new { caUserId = Guid.NewGuid().ToString() };
        var response = await _client.PostAsJsonAsync($"/itr/filings/{filingId}/ca-approve", approveRequest);

        response.StatusCode.Should().Be(HttpStatusCode.Conflict);
    }

    // ──────────────────────────────────────────────────────────────
    // Helpers
    // ──────────────────────────────────────────────────────────────

    private async Task<string> CreateAssesseeAsync()
    {
        var request = new
        {
            userId = Guid.NewGuid().ToString(),
            panLast4 = "1234",
            fullName = "Test Assessee",
            assesseeType = "INDIVIDUAL",
        };
        var response = await _client.PostAsJsonAsync("/itr/assessees", request);
        response.EnsureSuccessStatusCode();
        var body = await response.Content.ReadFromJsonAsync<JsonElement>();
        return body.GetProperty("id").GetString()!;
    }

    private async Task<string> CreateFilingAsync(string assesseeId, string ay, string regime)
    {
        var request = new
        {
            assesseeId,
            assessmentYear = ay,
            itrFormType = "ITR-1",
            regime,
        };
        var response = await _client.PostAsJsonAsync("/itr/filings", request);
        response.EnsureSuccessStatusCode();
        var body = await response.Content.ReadFromJsonAsync<JsonElement>();
        return body.GetProperty("id").GetString()!;
    }

    private async Task<JsonElement> GetFilingAsync(string filingId)
    {
        var response = await _client.GetAsync($"/itr/filings/{filingId}");
        response.EnsureSuccessStatusCode();
        return await response.Content.ReadFromJsonAsync<JsonElement>();
    }
}

/// <summary>
/// Integration tests for CA reject and re-submission flow.
/// </summary>
[Collection("ItrApi")]
public class FilingCaRejectIntegrationTests : IAsyncLifetime
{
    private readonly PostgreSqlContainer _postgres = new PostgreSqlBuilder()
        .WithImage("postgres:17-alpine")
        .WithDatabase("snapaccount_test_reject")
        .WithUsername("postgres")
        .WithPassword("postgres_test")
        .Build();

    private HttpClient _client = null!;
    private WebApplicationFactory<Program> _factory = null!;

    public async Task InitializeAsync()
    {
        await _postgres.StartAsync();

        _factory = new WebApplicationFactory<Program>()
            .WithWebHostBuilder(builder =>
            {
                builder.UseEnvironment("Testing");
                builder.ConfigureServices(services =>
                {
                    services.RemoveAll<DbContextOptions>();
                    services.RemoveAll<DbContextOptions<ItrServiceDbContext>>();
                    services.AddDbContext<ItrServiceDbContext>(options =>
                        options.UseNpgsql(_postgres.GetConnectionString()));
                });
            });

        _client = _factory.CreateClient();

        using var scope = _factory.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<ItrServiceDbContext>();
        await db.Database.MigrateAsync();
    }

    public async Task DisposeAsync()
    {
        _client.Dispose();
        await _factory.DisposeAsync();
        await _postgres.DisposeAsync();
    }

    /// <summary>
    /// CA reject flow: CA rejects a filing in UNDER_CA_REVIEW status.
    /// The filing moves to REJECTED_BY_CA with the rejection reason persisted.
    /// </summary>
    [Fact(Skip = "P6-INT-02: InternalsVisibleTo not yet configured on ItrService.Api")]
    public async Task FilingStateMachine_CaReject_PersistsReason()
    {
        // Arrange — need a filing in UNDER_CA_REVIEW state
        // (In a real test we'd do full setup; here we create via direct DB seeding)
        // Stub: assert that the reject endpoint returns 409 for a non-existent filing
        var response = await _client.PostAsJsonAsync(
            $"/itr/filings/{Guid.NewGuid()}/ca-reject",
            new { caUserId = Guid.NewGuid().ToString(), reason = "Missing Form 16 data" });

        // A non-existent filing should return 404
        response.StatusCode.Should().Be(HttpStatusCode.NotFound);
    }
}
