namespace ReportService.Domain.Entities;

/// <summary>
/// Types of reports that can be generated by ReportService.
/// Phase 6C adds LoanPackage.
/// </summary>
public enum ReportType
{
    /// <summary>Trial Balance report.</summary>
    TrialBalance = 1,

    /// <summary>Profit and Loss statement.</summary>
    ProfitAndLoss = 2,

    /// <summary>Balance Sheet.</summary>
    BalanceSheet = 3,

    /// <summary>Cash Flow statement.</summary>
    CashFlow = 4,

    /// <summary>Tax Liability report (GST summary).</summary>
    TaxLiability = 5,

    /// <summary>Ledger by Account (detailed transaction ledger).</summary>
    LedgerByAccount = 6,

    /// <summary>
    /// Loan Application Package — composite PDF.
    /// Merges: GSTR-3B summary + P&amp;L + Balance Sheet + Bank Statement Summary + KYC documents.
    /// Watermark: "Generated by SnapAccount | Not a CA certification".
    /// </summary>
    LoanPackage = 7
}

/// <summary>Output format for a report job.</summary>
public enum ReportFormat
{
    /// <summary>PDF output (via QuestPDF).</summary>
    Pdf = 1,

    /// <summary>JSON output (structured data, no layout).</summary>
    Json = 2
}

/// <summary>Status of a report generation job.</summary>
public enum ReportJobStatus
{
    /// <summary>Job is queued and waiting to be processed.</summary>
    Queued = 1,

    /// <summary>Job is currently being processed.</summary>
    Processing = 2,

    /// <summary>Job completed successfully. GcsUri and Sha256HashHex are set.</summary>
    Completed = 3,

    /// <summary>Job failed. ErrorMessage is set.</summary>
    Failed = 4
}
