// NOTE FOR BACKEND-AGENT: To enable WebApplicationFactory<Program>,
// add the following to backend/Services/CallbackService/CallbackService.Api/CallbackService.Api.csproj:
//
//   <ItemGroup>
//     <InternalsVisibleTo Include="CallbackService.IntegrationTests" />
//   </ItemGroup>
//
// Without this, the implicit Program class generated by top-level statements
// is internal and not accessible to this test project.

using CallbackService.Domain.Enums;
using FluentAssertions;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc.Testing;
using Microsoft.EntityFrameworkCore;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.DependencyInjection.Extensions;
using System.Net;
using System.Net.Http.Json;
using System.Text.Json;
using Testcontainers.PostgreSql;
using Xunit;

namespace CallbackService.IntegrationTests;

/// <summary>
/// Integration tests for CallbackService state machine — valid transitions persist,
/// invalid transitions return Conflict. Uses real PostgreSQL via Testcontainers.
/// No mocked DB per CLAUDE.md.
/// Phase 6E.
/// </summary>
[Collection("CallbackApi")]
public class CallbackStateMachineTests : IAsyncLifetime
{
    private readonly PostgreSqlContainer _postgres = new PostgreSqlBuilder()
        .WithImage("postgres:17-alpine")
        .WithDatabase("snapaccount_test")
        .WithUsername("postgres")
        .WithPassword("postgres_test")
        .Build();

    private HttpClient _client = null!;
    private WebApplicationFactory<Program> _factory = null!;

    // ──────────────────────────────────────────────────────────────
    // IAsyncLifetime
    // ──────────────────────────────────────────────────────────────

    public async Task InitializeAsync()
    {
        await _postgres.StartAsync();

        _factory = new WebApplicationFactory<Program>()
            .WithWebHostBuilder(builder =>
            {
                builder.UseEnvironment("Testing");
                builder.ConfigureServices(services =>
                {
                    // Remove existing DbContext registration and substitute test container
                    services.RemoveAll(typeof(DbContextOptions<Infrastructure.Persistence.CallbackDbContext>));
                    services.AddDbContext<Infrastructure.Persistence.CallbackDbContext>(opts =>
                        opts.UseNpgsql(_postgres.GetConnectionString()));

                    // Remove real Firebase middleware for tests
                    services.RemoveAll(typeof(SnapAccount.Shared.Infrastructure.Auth.FirebaseAuthMiddleware));
                });
            });

        _client = _factory.CreateClient();

        // Apply EF Core migrations to the test database
        using var scope = _factory.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<Infrastructure.Persistence.CallbackDbContext>();
        await db.Database.MigrateAsync();
    }

    public async Task DisposeAsync()
    {
        _client.Dispose();
        await _factory.DisposeAsync();
        await _postgres.DisposeAsync();
    }

    // ──────────────────────────────────────────────────────────────
    // Happy path: create + assign + confirm + complete
    // ──────────────────────────────────────────────────────────────

    [Fact]
    public async Task RequestCallback_ValidPayload_Returns201WithPendingStatus()
    {
        var response = await _client.PostAsJsonAsync("/callbacks", new
        {
            phoneNumber = "+919876543210",
            category = "Gst",
            priority = "High",
            issueDescription = "GSTR-3B late fee query",
            userId = Guid.NewGuid(),
        });

        response.StatusCode.Should().Be(HttpStatusCode.Created);
        var body = await response.Content.ReadFromJsonAsync<JsonElement>();
        body.GetProperty("status").GetString().Should().Be("Pending");
    }

    [Fact]
    public async Task AssignCallback_FromPending_Returns200AndStatusBecomesAssigned()
    {
        var callbackId = await CreatePendingCallback();
        var agentId = Guid.NewGuid();

        var response = await _client.PostAsJsonAsync($"/callbacks/{callbackId}/assign",
            new { agentId });

        response.StatusCode.Should().Be(HttpStatusCode.OK);

        var detail = await _client.GetFromJsonAsync<JsonElement>($"/callbacks/{callbackId}");
        detail.GetProperty("status").GetString().Should().Be("Assigned");
    }

    [Fact]
    public async Task ConfirmCallback_FromAssigned_Returns200AndStatusBecomesConfirmed()
    {
        var callbackId = await CreatePendingCallback();
        var agentId = Guid.NewGuid();
        await _client.PostAsJsonAsync($"/callbacks/{callbackId}/assign", new { agentId });

        var scheduledAt = DateTime.UtcNow.AddHours(3).ToString("O");
        var response = await _client.PostAsJsonAsync($"/callbacks/{callbackId}/confirm",
            new { scheduledAt });

        response.StatusCode.Should().Be(HttpStatusCode.OK);
        var detail = await _client.GetFromJsonAsync<JsonElement>($"/callbacks/{callbackId}");
        detail.GetProperty("status").GetString().Should().Be("Confirmed");
    }

    [Fact]
    public async Task CompleteCallback_FromConfirmed_Returns200AndStatusBecomesCompleted()
    {
        var callbackId = await CreatePendingCallback();
        var agentId = Guid.NewGuid();
        await _client.PostAsJsonAsync($"/callbacks/{callbackId}/assign", new { agentId });
        await _client.PostAsJsonAsync($"/callbacks/{callbackId}/confirm",
            new { scheduledAt = DateTime.UtcNow.AddHours(2).ToString("O") });

        var response = await _client.PostAsJsonAsync($"/callbacks/{callbackId}/complete",
            new { resolutionSummary = "Issue resolved — GSTR-3B late fee waived." });

        response.StatusCode.Should().Be(HttpStatusCode.OK);
        var detail = await _client.GetFromJsonAsync<JsonElement>($"/callbacks/{callbackId}");
        detail.GetProperty("status").GetString().Should().Be("Completed");
    }

    // ──────────────────────────────────────────────────────────────
    // Invalid transitions → Conflict
    // ──────────────────────────────────────────────────────────────

    [Fact]
    public async Task CompleteCallback_FromPending_Returns409Conflict()
    {
        var callbackId = await CreatePendingCallback();

        // Attempt to complete directly from Pending (invalid — must go via Assigned/Confirmed)
        var response = await _client.PostAsJsonAsync($"/callbacks/{callbackId}/complete",
            new { resolutionSummary = "Premature completion attempt." });

        response.StatusCode.Should().Be(HttpStatusCode.Conflict);
    }

    [Fact]
    public async Task AssignCallback_WhenAlreadyAssigned_Returns409Conflict()
    {
        var callbackId = await CreatePendingCallback();
        await _client.PostAsJsonAsync($"/callbacks/{callbackId}/assign", new { agentId = Guid.NewGuid() });

        // Second assign from Assigned state is invalid
        var response = await _client.PostAsJsonAsync($"/callbacks/{callbackId}/assign",
            new { agentId = Guid.NewGuid() });

        response.StatusCode.Should().Be(HttpStatusCode.Conflict);
    }

    [Fact]
    public async Task ConfirmCallback_FromPending_Returns409Conflict()
    {
        var callbackId = await CreatePendingCallback();

        // Must be Assigned before confirming
        var response = await _client.PostAsJsonAsync($"/callbacks/{callbackId}/confirm",
            new { scheduledAt = DateTime.UtcNow.AddHours(1).ToString("O") });

        response.StatusCode.Should().Be(HttpStatusCode.Conflict);
    }

    [Fact]
    public async Task CancelCallback_AfterCompleted_Returns409Conflict()
    {
        var callbackId = await CreatePendingCallback();
        var agentId = Guid.NewGuid();
        await _client.PostAsJsonAsync($"/callbacks/{callbackId}/assign", new { agentId });
        await _client.PostAsJsonAsync($"/callbacks/{callbackId}/confirm",
            new { scheduledAt = DateTime.UtcNow.AddHours(1).ToString("O") });
        await _client.PostAsJsonAsync($"/callbacks/{callbackId}/complete",
            new { resolutionSummary = "Done" });

        // Cannot cancel after completion
        var response = await _client.PostAsJsonAsync($"/callbacks/{callbackId}/cancel",
            new { reason = "Too late" });

        response.StatusCode.Should().Be(HttpStatusCode.Conflict);
    }

    // ──────────────────────────────────────────────────────────────
    // Escalate — valid from Pending
    // ──────────────────────────────────────────────────────────────

    [Fact]
    public async Task EscalateCallback_FromPending_Returns200AndStatusBecomesEscalated()
    {
        var callbackId = await CreatePendingCallback();

        var response = await _client.PostAsJsonAsync($"/callbacks/{callbackId}/escalate",
            new { reason = "Complex ITR query — needs senior CA" });

        response.StatusCode.Should().Be(HttpStatusCode.OK);
        var detail = await _client.GetFromJsonAsync<JsonElement>($"/callbacks/{callbackId}");
        detail.GetProperty("status").GetString().Should().Be("Escalated");
    }

    // ──────────────────────────────────────────────────────────────
    // Add note
    // ──────────────────────────────────────────────────────────────

    [Fact]
    public async Task AddNote_ValidContent_Returns201WithNoteId()
    {
        var callbackId = await CreatePendingCallback();

        var response = await _client.PostAsJsonAsync($"/callbacks/{callbackId}/notes", new
        {
            content = "Called the customer — line was busy, will try again in 30 minutes.",
            isInternal = false,
            outcome = "NO_ANSWER",
            durationMinutes = 2,
        });

        response.StatusCode.Should().Be(HttpStatusCode.Created);
        var body = await response.Content.ReadFromJsonAsync<JsonElement>();
        body.GetProperty("id").GetString().Should().NotBeNullOrWhiteSpace();
    }

    // ──────────────────────────────────────────────────────────────
    // Validation errors
    // ──────────────────────────────────────────────────────────────

    [Fact]
    public async Task RequestCallback_InvalidPhoneFormat_Returns400()
    {
        var response = await _client.PostAsJsonAsync("/callbacks", new
        {
            phoneNumber = "9876543210",  // missing +91
            category = "Gst",
            priority = "Normal",
            userId = Guid.NewGuid(),
        });

        response.StatusCode.Should().Be(HttpStatusCode.BadRequest);
    }

    [Fact]
    public async Task GetCallback_NonExistentId_Returns404()
    {
        var response = await _client.GetAsync($"/callbacks/{Guid.NewGuid()}");

        response.StatusCode.Should().Be(HttpStatusCode.NotFound);
    }

    // ──────────────────────────────────────────────────────────────
    // List callbacks
    // ──────────────────────────────────────────────────────────────

    [Fact]
    public async Task ListCallbacks_Returns200WithPaginatedResult()
    {
        await CreatePendingCallback();
        await CreatePendingCallback();

        var response = await _client.GetAsync("/callbacks?page=1&size=10");

        response.StatusCode.Should().Be(HttpStatusCode.OK);
        var body = await response.Content.ReadFromJsonAsync<JsonElement>();
        body.GetProperty("items").GetArrayLength().Should().BeGreaterThanOrEqualTo(2);
    }

    // ──────────────────────────────────────────────────────────────
    // Helper
    // ──────────────────────────────────────────────────────────────

    private async Task<Guid> CreatePendingCallback()
    {
        var response = await _client.PostAsJsonAsync("/callbacks", new
        {
            phoneNumber = "+919876543210",
            category = "Gst",
            priority = "Normal",
            issueDescription = "Integration test callback",
            userId = Guid.NewGuid(),
        });

        response.EnsureSuccessStatusCode();
        var body = await response.Content.ReadFromJsonAsync<JsonElement>();
        return Guid.Parse(body.GetProperty("callbackId").GetString()!);
    }
}

// ──────────────────────────────────────────────────────────────────────────────
// SEC-029: IDOR / cross-org access tests
// ──────────────────────────────────────────────────────────────────────────────

/// <summary>
/// SEC-029: Verifies that callback endpoints return 404 when accessed by a user
/// whose OrganizationId does not match the callback's organization.
/// Uses a shared Postgres container via [Collection("CallbackApi")].
/// </summary>
[Collection("CallbackApi")]
public class CallbackIdrSecurityTests : IAsyncLifetime
{
    private readonly PostgreSqlContainer _postgres = new PostgreSqlBuilder()
        .WithImage("postgres:17-alpine")
        .WithDatabase("snapaccount_sec_test")
        .WithUsername("postgres")
        .WithPassword("postgres_test")
        .Build();

    private HttpClient _client = null!;
    private WebApplicationFactory<Program> _factory = null!;

    public async Task InitializeAsync()
    {
        await _postgres.StartAsync();

        _factory = new WebApplicationFactory<Program>()
            .WithWebHostBuilder(builder =>
            {
                builder.UseEnvironment("Testing");
                builder.ConfigureServices(services =>
                {
                    services.RemoveAll(typeof(DbContextOptions<Infrastructure.Persistence.CallbackDbContext>));
                    services.AddDbContext<Infrastructure.Persistence.CallbackDbContext>(opts =>
                        opts.UseNpgsql(_postgres.GetConnectionString()));

                    services.RemoveAll(typeof(SnapAccount.Shared.Infrastructure.Auth.FirebaseAuthMiddleware));

                    // SEC-029: override ICurrentUser to inject a specific org context per test
                    services.RemoveAll(typeof(SnapAccount.Shared.Application.ICurrentUser));
                    services.AddScoped<SnapAccount.Shared.Application.ICurrentUser, TestCurrentUser>();
                });
            });

        _client = _factory.CreateClient();

        using var scope = _factory.Services.CreateScope();
        var db = scope.ServiceProvider.GetRequiredService<Infrastructure.Persistence.CallbackDbContext>();
        await db.Database.MigrateAsync();
    }

    public async Task DisposeAsync()
    {
        _client.Dispose();
        await _factory.DisposeAsync();
        await _postgres.DisposeAsync();
    }

    /// <summary>
    /// SEC-029: GET /callbacks/{id} for a callback belonging to a different org returns 404.
    /// Prevents existence leak — attacker learns nothing about cross-org resources.
    /// </summary>
    [Fact]
    public async Task GetCallback_CrossOrgAccess_Returns404()
    {
        // Create a callback with org A
        var orgA = Guid.NewGuid();
        TestCurrentUser.CurrentOrgId = orgA;

        var createResponse = await _client.PostAsJsonAsync("/callbacks", new
        {
            phoneNumber = "+919876543210",
            category = "Gst",
            priority = "Normal",
            issueDescription = "Belongs to org A",
            userId = Guid.NewGuid(),
            organizationId = orgA,
        });
        createResponse.EnsureSuccessStatusCode();
        var body = await createResponse.Content.ReadFromJsonAsync<JsonElement>();
        var callbackId = Guid.Parse(body.GetProperty("callbackId").GetString()!);

        // Switch to org B — should not be able to see org A's callback
        TestCurrentUser.CurrentOrgId = Guid.NewGuid();
        var response = await _client.GetAsync($"/callbacks/{callbackId}");

        response.StatusCode.Should().Be(HttpStatusCode.NotFound,
            "SEC-029: cross-org GET must return 404 to prevent existence leak");
    }

    /// <summary>
    /// SEC-029: POST /callbacks/{id}/assign for a cross-org callback returns 404.
    /// </summary>
    [Fact]
    public async Task AssignCallback_CrossOrgAccess_Returns404()
    {
        var orgA = Guid.NewGuid();
        TestCurrentUser.CurrentOrgId = orgA;

        var createResponse = await _client.PostAsJsonAsync("/callbacks", new
        {
            phoneNumber = "+919876543210",
            category = "Accounting",
            priority = "High",
            issueDescription = "Belongs to org A",
            userId = Guid.NewGuid(),
            organizationId = orgA,
        });
        createResponse.EnsureSuccessStatusCode();
        var body = await createResponse.Content.ReadFromJsonAsync<JsonElement>();
        var callbackId = Guid.Parse(body.GetProperty("callbackId").GetString()!);

        // Org B tries to assign
        TestCurrentUser.CurrentOrgId = Guid.NewGuid();
        var response = await _client.PostAsJsonAsync($"/callbacks/{callbackId}/assign",
            new { agentId = Guid.NewGuid() });

        response.StatusCode.Should().Be(HttpStatusCode.NotFound,
            "SEC-029: cross-org assign must return 404 to prevent existence leak");
    }

    /// <summary>
    /// SEC-029: Same-org access to GET /callbacks/{id} returns 200 (control case).
    /// </summary>
    [Fact]
    public async Task GetCallback_SameOrgAccess_Returns200()
    {
        var orgId = Guid.NewGuid();
        TestCurrentUser.CurrentOrgId = orgId;

        var createResponse = await _client.PostAsJsonAsync("/callbacks", new
        {
            phoneNumber = "+919876543210",
            category = "Itr",
            priority = "Normal",
            issueDescription = "Belongs to same org",
            userId = Guid.NewGuid(),
            organizationId = orgId,
        });
        createResponse.EnsureSuccessStatusCode();
        var body = await createResponse.Content.ReadFromJsonAsync<JsonElement>();
        var callbackId = Guid.Parse(body.GetProperty("callbackId").GetString()!);

        // Same org — should succeed
        var response = await _client.GetAsync($"/callbacks/{callbackId}");

        response.StatusCode.Should().Be(HttpStatusCode.OK,
            "SEC-029: same-org GET must succeed");
    }
}

/// <summary>
/// SEC-029 test helper: a thread-static ICurrentUser that allows tests to set the org context.
/// </summary>
public sealed class TestCurrentUser : SnapAccount.Shared.Application.ICurrentUser
{
    [ThreadStatic]
    public static Guid? CurrentOrgId;

    [ThreadStatic]
    public static Guid? CurrentUserId;

    public Guid UserId => CurrentUserId ?? Guid.NewGuid();
    public Guid? OrganizationId => CurrentOrgId;
    public IReadOnlyList<string> Roles => [];
    // SEC-026/028: grant all permissions ("*") so the permission gate does not block IDOR tests
    public IReadOnlyList<string> Permissions => ["*"];
    public bool IsAuthenticated => true;
    public string? FirebaseUid => null;
    public string? PhoneNumber => null;
    public string? Email => null;

    public bool IsInRole(string role) => false;
    // SEC-026/028: in these IDOR tests grant all permissions so permission gate does not block
    public bool HasPermission(string permission) => true;
}
