using SnapAccount.Shared.Domain;
using DocumentService.Domain.Events;

namespace DocumentService.Domain.Entities;

public class Document : BaseAuditableEntity
{
    // DG-SEC-03: UserId is nullable to support DPDP right-to-erasure — the subscriber
    // NULLs this field when the account owner's deletion event fires. The DB column is
    // widened to UUID NULL in migration 093_document_dpdp_erasure.sql.
    public Guid? UserId { get; set; }
    public Guid? OrganizationId { get; init; }
    public Guid? CategoryId { get; set; }
    public string FileName { get; init; } = string.Empty;
    // DG-SEC-03: OriginalFileName is settable so the DPDP subscriber can clear it on erasure.
    public string? OriginalFileName { get; set; }
    public string MimeType { get; init; } = string.Empty;
    public long? FileSizeBytes { get; init; }
    public string? StorageBucket { get; init; }
    public string StoragePath { get; init; } = string.Empty;
    public string? StorageUrl { get; private set; }
    public int PageCount { get; private set; } = 1;
    public DateOnly? DocumentDate { get; private set; }
    public string? VendorName { get; private set; }
    public decimal? Amount { get; private set; }
    public string Status { get; private set; } = "UPLOADED";
    // UPLOADED, OCR_IN_PROGRESS, OCR_COMPLETE, IN_REVIEW, APPROVED, PROCESSED, REJECTED, ARCHIVED
    public bool IsEncrypted { get; private set; } = true;
    public string? EncryptionKeyId { get; private set; }
    public DateTime UploadedAt { get; private set; } = DateTime.UtcNow;
    public DateTime? ProcessedAt { get; private set; }
    public DateTime? ArchivedAt { get; private set; }

    /// <summary>Populated by <see cref="Reject"/> — reason the operator supplied.</summary>
    public string? RejectionReason { get; private set; }

    /// <summary>Populated by <see cref="Approve"/> — ID of the operator who approved.</summary>
    public Guid? ApprovedBy { get; private set; }

    /// <summary>Populated by <see cref="Approve"/> — UTC timestamp of approval.</summary>
    public DateTime? ApprovedAt { get; private set; }

    // ── DPDP Act 2023 Right-to-Erasure fields (DG-SEC-03) ────────────────────────────
    // Set by AccountDeletionSubscriber when the document owner's account is deleted.
    // UserId is nulled and file-name/OCR-PII is cleared; the row is kept for audit
    // (document.original_file_name carries the only user-visible PII that is cleared).

    /// <summary>
    /// UTC timestamp when DPDP erasure was applied to this document row.
    /// Null means the document has not been anonymised.
    /// </summary>
    public DateTime? AnonymizedAt { get; set; }

    /// <summary>
    /// Reason code for anonymisation — always 'DPDP_USER_ERASURE' for right-to-erasure.
    /// </summary>
    public string? AnonymizationReason { get; set; }

    /// <summary>
    /// DG-DOC-08: Client-supplied idempotency key (UUID v4) for upload deduplication.
    /// Generated by the mobile client on enqueue and sent as the <c>Idempotency-Key</c>
    /// request header (or form field). On repeat uploads with the same key the backend
    /// returns the existing document (200) instead of creating a duplicate row.
    /// Nullable: documents uploaded without a key (legacy / web) do not participate in
    /// idempotency deduplication.
    /// Unique constraint: (organization_id, idempotency_key) — see migration 107.
    /// </summary>
    public string? IdempotencyKey { get; set; }

    /// <summary>Valid inbound statuses for an operator review decision.</summary>
    private static readonly IReadOnlySet<string> ReviewableStatuses =
        new HashSet<string>(StringComparer.OrdinalIgnoreCase) { "OCR_COMPLETE", "IN_REVIEW" };

    public void StartOcr()
    {
        Status = "OCR_IN_PROGRESS";
    }

    public void CompleteOcr(decimal? amount, string? vendorName, DateOnly? documentDate)
    {
        Status = "OCR_COMPLETE";
        Amount = amount;
        VendorName = vendorName;
        DocumentDate = documentDate;
        // UserId is Guid? (nullable since DG-SEC-03 erasure support); erased docs have Guid.Empty.
        AddDomainEvent(new OcrCompletedEvent(Id, UserId ?? Guid.Empty, OrganizationId));
    }

    public void MarkProcessed()
    {
        Status = "PROCESSED";
        ProcessedAt = DateTime.UtcNow;
        AddDomainEvent(new DocumentProcessedEvent(Id, UserId ?? Guid.Empty));
    }

    public void Archive()
    {
        Status = "ARCHIVED";
        ArchivedAt = DateTime.UtcNow;
    }

    /// <summary>
    /// Transitions the document to REJECTED.
    /// Valid from any non-terminal status (ARCHIVED/APPROVED are terminal).
    /// </summary>
    public void Reject(string reason)
    {
        RejectionReason = reason;
        Status = "REJECTED";
    }

    /// <summary>
    /// Approves an OCR-reviewed document and raises <see cref="DocumentApprovedEvent"/>
    /// which carries the accounting payload for AccountingService.
    /// Valid from OCR_COMPLETE or IN_REVIEW only.
    /// </summary>
    /// <param name="approvedBy">UserId of the operator performing the approval.</param>
    /// <exception cref="InvalidOperationException">Thrown when document is not in a reviewable status.</exception>
    public void Approve(Guid approvedBy)
    {
        if (!ReviewableStatuses.Contains(Status))
            throw new InvalidOperationException(
                $"Document {Id} cannot be approved from status '{Status}'. " +
                $"Valid statuses: {string.Join(", ", ReviewableStatuses)}.");

        ApprovedBy = approvedBy;
        ApprovedAt = DateTime.UtcNow;
        Status = "APPROVED";
        AddDomainEvent(new DocumentApprovedEvent(
            DocumentId: Id,
            UserId: UserId ?? Guid.Empty,
            OrganizationId: OrganizationId,
            ApprovedBy: approvedBy,
            TotalAmount: Amount ?? 0m,
            VendorName: VendorName,
            DocumentDate: DocumentDate ?? DateOnly.FromDateTime(UploadedAt)));
    }

    /// <summary>
    /// Requests clarification from the document owner.
    /// Can be called from any non-terminal status.
    /// </summary>
    public void RequestClarification() { /* status stays unchanged */ }
}
