using FluentValidation;
using LoanService.Application.Common.Interfaces;
using LoanService.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using SnapAccount.Shared.Application;
using SnapAccount.Shared.Application.Behaviors;
using SnapAccount.Shared.Domain;

namespace LoanService.Application.LoanApplications.Commands.GeneratePackage;

/// <summary>
/// Generates the loan application PDF package and stores it to GCS.
/// Watermark: "Generated by SnapAccount | {orgName} | {date} | Package ID: {id} | Not a CA certification"
/// Disclaimer footer: "Prepared by SnapAccount from user-provided data. Not a CA certification.
///                     Final lending decision rests with the partner bank."
/// </summary>
[RequiresPermission("loan.package.generate")]
public record GeneratePackageCommand(
    Guid ApplicationId,
    string OrgName) : ICommand<GeneratePackageResponse>;

/// <summary>Response after PDF package generation.</summary>
public record GeneratePackageResponse(
    Guid PackageId,
    string GcsUri,
    int PageCount,
    string Sha256HashHex,
    string SignedDownloadUrl);

/// <summary>Validates GeneratePackageCommand.</summary>
public sealed class GeneratePackageCommandValidator : AbstractValidator<GeneratePackageCommand>
{
    public GeneratePackageCommandValidator()
    {
        RuleFor(x => x.ApplicationId).NotEmpty();
        RuleFor(x => x.OrgName).NotEmpty().MaximumLength(200);
    }
}

/// <summary>Handler: generates PDF, uploads to GCS, records in loan.pdf_packages.</summary>
public sealed class GeneratePackageCommandHandler(
    ILoanServiceDbContext db,
    ICurrentUser currentUser,
    ILoanPdfGenerator pdfGenerator,
    ILoanStorageService cloudStorage) : ICommandHandler<GeneratePackageCommand, GeneratePackageResponse>
{
    private const string LoanPackagesBucket = "GCS_LOAN_PACKAGES_BUCKET";

    /// <inheritdoc />
    public async Task<Result<GeneratePackageResponse>> Handle(
        GeneratePackageCommand request,
        CancellationToken cancellationToken)
    {
        var orgId = currentUser.OrganizationId;
        if (!orgId.HasValue)
            return Result<GeneratePackageResponse>.Failure(
                Error.Validation("LoanApplication.NoOrg", "User is not associated with an organisation."));

        // IDOR: filter by org
        var application = await db.LoanApplications
            .Where(a => a.Id == request.ApplicationId && a.OrgId == orgId.Value && a.DeletedAt == null)
            .FirstOrDefaultAsync(cancellationToken);

        if (application == null)
            return Error.NotFound("LoanApplication", request.ApplicationId);

        // Mark previous packages as not-current
        var previousPackages = await db.LoanPdfPackages
            .Where(p => p.ApplicationId == request.ApplicationId && p.IsCurrent)
            .ToListAsync(cancellationToken);
        foreach (var prev in previousPackages)
            prev.IsCurrent = false;

        // Generate the PDF
        (byte[] pdfBytes, byte[] sha256Hash, int pageCount) = await pdfGenerator.GenerateAsync(
            request.ApplicationId, orgId.Value, request.OrgName, cancellationToken);

        // Package ID is generated by BaseEntity on construction
        var package = new LoanPdfPackage
        {
            ApplicationId = request.ApplicationId,
            GcsUri = "placeholder", // set after upload with real URI
            PagesCount = pageCount,
            Sha256Hash = sha256Hash,
            GeneratedAt = DateTime.UtcNow,
            GeneratedBy = currentUser.UserId,
            WatermarkText = $"Generated by SnapAccount | {request.OrgName} | {DateTime.UtcNow:yyyy-MM-dd} | Package ID: (pending) | Not a CA certification",
            IsCurrent = true
        };
        var packageId = package.Id;

        // Upload to GCS using the now-known packageId
        var objectName = $"loan-packages/{request.ApplicationId}/{packageId}.pdf";
        var bucketName = Environment.GetEnvironmentVariable(LoanPackagesBucket)
            ?? "snapaccount-loan-packages-dev";
        var gcsUri = await cloudStorage.UploadAsync(bucketName, objectName, pdfBytes, "application/pdf", cancellationToken);

        package.GcsUri = gcsUri;
        package.WatermarkText = $"Generated by SnapAccount | {request.OrgName} | {DateTime.UtcNow:yyyy-MM-dd} | Package ID: {packageId} | Not a CA certification";

        db.LoanPdfPackages.Add(package);
        await db.SaveChangesAsync(cancellationToken);

        var signedUrl = await cloudStorage.GetSignedDownloadUrlAsync(bucketName, objectName, TimeSpan.FromHours(1), cancellationToken);

        return new GeneratePackageResponse(
            packageId,
            gcsUri,
            pageCount,
            Convert.ToHexString(sha256Hash).ToLowerInvariant(),
            signedUrl);
    }
}
