using SnapAccount.Shared.Domain;

namespace GstService.Domain.Entities;

/// <summary>
/// Represents an inward invoice visible in the GSTN Invoice Management System (IMS).
/// Regulatory context (mandatory from 1 Apr 2026, CGST circular 2025): taxpayers must
/// accept, reject, or mark as pending each supplier-reported inward invoice BEFORE
/// GSTR-2B is generated. The status drives ITC eligibility.
/// </summary>
/// <remarks>
/// State machine:
///   PENDING → ACCEPTED | REJECTED | PENDING_KEPT
///   PENDING_KEPT → ACCEPTED | REJECTED (taxpayer may act later)
///   ACCEPTED / REJECTED — terminal until GSTR-2B is generated (then deemed-acceptance sweep freezes)
///
/// Deemed acceptance: if the invoice remains PENDING when GSTR-2B is generated by GSTN,
/// it is automatically deemed ACCEPTED. The <see cref="DeemedAccepted"/> flag marks this
/// post-hoc transition; <see cref="Status"/> is set to ACCEPTED at the same time.
/// </remarks>
public sealed class ImsInvoice : BaseAuditableEntity
{
    /// <summary>Organisation (GSTIN holder) this invoice belongs to.</summary>
    public Guid OrganizationId { get; private set; }

    /// <summary>GSTIN of the supplier who reported this invoice.</summary>
    public string SupplierGstin { get; private set; } = string.Empty;

    /// <summary>Supplier legal name as reported on GSTN.</summary>
    public string SupplierName { get; private set; } = string.Empty;

    /// <summary>Invoice number as reported by the supplier.</summary>
    public string InvoiceNumber { get; private set; } = string.Empty;

    /// <summary>Invoice date (DateOnly — no time component in GST).</summary>
    public DateOnly InvoiceDate { get; private set; }

    /// <summary>Total invoice value (taxable + taxes) in INR. Always decimal, never float.</summary>
    public decimal InvoiceValue { get; private set; }

    // ── Tax heads (INR) ──────────────────────────────────────────────────────

    /// <summary>Taxable value on the invoice (before taxes).</summary>
    public decimal TaxableValue { get; private set; }

    /// <summary>Integrated GST amount.</summary>
    public decimal IgstAmount { get; private set; }

    /// <summary>Central GST amount.</summary>
    public decimal CgstAmount { get; private set; }

    /// <summary>State/UT GST amount.</summary>
    public decimal SgstAmount { get; private set; }

    /// <summary>GST Cess amount.</summary>
    public decimal CessAmount { get; private set; }

    // ── Period / Source ──────────────────────────────────────────────────────

    /// <summary>
    /// Return period in MMYYYY format (e.g. "032026" for March 2026).
    /// Matches the GSTN API period convention.
    /// </summary>
    public string Period { get; private set; } = string.Empty;

    /// <summary>
    /// Source form on which the supplier reported this invoice.
    /// Values: "GSTR-1", "IFF" (Invoice Furnishing Facility).
    /// </summary>
    public string Source { get; private set; } = string.Empty;

    // ── IMS Action State ─────────────────────────────────────────────────────

    /// <summary>
    /// Current IMS action status.
    /// Values: PENDING | ACCEPTED | REJECTED | PENDING_KEPT
    /// </summary>
    public string Status { get; private set; } = "PENDING";

    /// <summary>UTC timestamp when a taxpayer action was last taken. Null if still PENDING.</summary>
    public DateTime? ActionedAt { get; private set; }

    /// <summary>User ID of the taxpayer who last actioned. Null if still PENDING.</summary>
    public Guid? ActionedBy { get; private set; }

    /// <summary>
    /// True if the invoice was automatically deemed ACCEPTED at GSTR-2B generation time
    /// because no explicit action was taken. Set by the deemed-acceptance sweep command.
    /// </summary>
    public bool DeemedAccepted { get; private set; }

    /// <summary>
    /// Optional reason provided by the taxpayer when rejecting an invoice
    /// (free text, stored for audit purposes).
    /// </summary>
    public string? RejectionReason { get; private set; }

    private ImsInvoice() { } // EF Core

    /// <summary>
    /// Factory — creates a new IMS invoice in PENDING status.
    /// Called by the FetchImsInvoicesCommand when syncing from GSTN (or mock).
    /// </summary>
    public static ImsInvoice Create(
        Guid organizationId,
        string supplierGstin,
        string supplierName,
        string invoiceNumber,
        DateOnly invoiceDate,
        decimal invoiceValue,
        decimal taxableValue,
        decimal igstAmount,
        decimal cgstAmount,
        decimal sgstAmount,
        decimal cessAmount,
        string period,
        string source)
    {
        return new ImsInvoice
        {
            OrganizationId = organizationId,
            SupplierGstin = supplierGstin,
            SupplierName = supplierName,
            InvoiceNumber = invoiceNumber,
            InvoiceDate = invoiceDate,
            InvoiceValue = invoiceValue,
            TaxableValue = taxableValue,
            IgstAmount = igstAmount,
            CgstAmount = cgstAmount,
            SgstAmount = sgstAmount,
            CessAmount = cessAmount,
            Period = period,
            Source = source,
            Status = "PENDING",
            DeemedAccepted = false
        };
    }

    // ── State machine ────────────────────────────────────────────────────────

    /// <summary>
    /// Accepts the inward invoice for ITC claim.
    /// Idempotent: accepting an already-ACCEPTED invoice is a no-op (returns success).
    /// Cannot accept a REJECTED invoice.
    /// </summary>
    public Result Accept(Guid actionedBy)
    {
        if (Status == "ACCEPTED")
            return Result.Success(); // idempotent

        if (Status == "REJECTED")
            return Result.Failure(Error.Conflict(
                "ImsInvoice.InvalidTransition",
                "Cannot accept a rejected invoice. Raise a GSTR-1A amendment to correct the supplier's return."));

        Status = "ACCEPTED";
        ActionedAt = DateTime.UtcNow;
        ActionedBy = actionedBy;
        DeemedAccepted = false;
        return Result.Success();
    }

    /// <summary>
    /// Rejects the inward invoice (ITC will not flow into GSTR-2B).
    /// Idempotent: rejecting an already-REJECTED invoice is a no-op (returns success).
    /// Cannot reject an ACCEPTED invoice — taxpayer must use GSTR-1A amendment workflow.
    /// </summary>
    public Result Reject(Guid actionedBy, string? reason)
    {
        if (Status == "REJECTED")
            return Result.Success(); // idempotent

        if (Status == "ACCEPTED" && !DeemedAccepted)
            return Result.Failure(Error.Conflict(
                "ImsInvoice.InvalidTransition",
                "Cannot reject an accepted invoice. Create a GSTR-1A amendment to correct the supplier's return."));

        Status = "REJECTED";
        ActionedAt = DateTime.UtcNow;
        ActionedBy = actionedBy;
        RejectionReason = reason;
        return Result.Success();
    }

    /// <summary>
    /// Marks the invoice as PENDING_KEPT — taxpayer has acknowledged it but deferred decision.
    /// Idempotent: calling on already-PENDING_KEPT is a no-op.
    /// Not applicable once a terminal action (ACCEPTED/REJECTED) has been taken.
    /// </summary>
    public Result KeepPending(Guid actionedBy)
    {
        if (Status == "PENDING_KEPT")
            return Result.Success(); // idempotent

        if (Status is "ACCEPTED" or "REJECTED")
            return Result.Failure(Error.Conflict(
                "ImsInvoice.InvalidTransition",
                $"Cannot mark as pending-kept from status '{Status}'."));

        Status = "PENDING_KEPT";
        ActionedAt = DateTime.UtcNow;
        ActionedBy = actionedBy;
        return Result.Success();
    }

    /// <summary>
    /// Applies deemed acceptance — called by the scheduled sweep at GSTR-2B generation time.
    /// Invoices in PENDING or PENDING_KEPT status are deemed ACCEPTED per GSTN rules.
    /// Already-ACCEPTED or REJECTED invoices are not modified.
    /// </summary>
    /// <returns>True if the invoice was changed; false if already in a terminal state.</returns>
    public bool ApplyDeemedAcceptance()
    {
        if (Status is "ACCEPTED" or "REJECTED")
            return false;

        Status = "ACCEPTED";
        DeemedAccepted = true;
        ActionedAt = DateTime.UtcNow;
        return true;
    }
}
