using FluentValidation;
using LoanService.Application.Common.Interfaces;
using LoanService.Domain.Entities;
using Microsoft.EntityFrameworkCore;
using ReportService.Application.Common.Interfaces;
using ReportService.Domain.Entities;
using SnapAccount.Shared.Application;
using SnapAccount.Shared.Application.Behaviors;
using SnapAccount.Shared.Domain;

namespace LoanService.Application.LoanApplications.Commands.GeneratePackage;

/// <summary>
/// Generates the loan application PDF package using the real Report pipeline.
///
/// DG-LOAN-03: wired to IReportGenerator (ReportType.LoanPackage) via IReportServiceDbContext.
/// Both LoanService and ReportService are co-hosted in the Finance composite, so their
/// DI registrations are available in the same container.
///
/// Watermark: "Generated by SnapAccount | {orgName} | {date} | Package ID: {id} | Not a CA certification"
/// Disclaimer footer: "Prepared by SnapAccount from user-provided data. Not a CA certification.
///                     Final lending decision rests with the partner bank."
/// </summary>
[RequiresPermission("loan.package.generate")]
public record GeneratePackageCommand(
    Guid ApplicationId,
    string OrgName) : ICommand<GeneratePackageResponse>;

/// <summary>Response after PDF package generation.</summary>
public record GeneratePackageResponse(
    Guid PackageId,
    string GcsUri,
    int PageCount,
    string Sha256HashHex,
    string SignedDownloadUrl);

/// <summary>Validates GeneratePackageCommand.</summary>
public sealed class GeneratePackageCommandValidator : AbstractValidator<GeneratePackageCommand>
{
    public GeneratePackageCommandValidator()
    {
        RuleFor(x => x.ApplicationId).NotEmpty();
        RuleFor(x => x.OrgName).NotEmpty().MaximumLength(200);
    }
}

/// <summary>
/// DG-LOAN-03: Handler uses the Report module's IReportGenerator pipeline (ReportType.LoanPackage)
/// instead of the stub ILoanPdfGenerator, so real org financials flow into the PDF.
/// </summary>
public sealed class GeneratePackageCommandHandler(
    ILoanServiceDbContext db,
    IReportServiceDbContext reportDb,
    ICurrentUser currentUser,
    IEnumerable<IReportGenerator> reportGenerators,
    ILoanStorageService cloudStorage) : ICommandHandler<GeneratePackageCommand, GeneratePackageResponse>
{
    private const string LoanPackagesBucket = "GCS_LOAN_PACKAGES_BUCKET";

    /// <inheritdoc />
    public async Task<Result<GeneratePackageResponse>> Handle(
        GeneratePackageCommand request,
        CancellationToken cancellationToken)
    {
        var orgId = currentUser.OrganizationId;
        if (!orgId.HasValue)
            return Result<GeneratePackageResponse>.Failure(
                Error.Validation("LoanApplication.NoOrg", "User is not associated with an organisation."));

        // IDOR: filter by org
        var application = await db.LoanApplications
            .Where(a => a.Id == request.ApplicationId && a.OrgId == orgId.Value && a.DeletedAt == null)
            .FirstOrDefaultAsync(cancellationToken);

        if (application == null)
            return Error.NotFound("LoanApplication", request.ApplicationId);

        // DG-LOAN-03: find the LoanPackage PDF generator via the Report pipeline
        var generator = reportGenerators.FirstOrDefault(
            g => g.Supports(ReportType.LoanPackage, ReportFormat.Pdf));

        if (generator == null)
            return Result<GeneratePackageResponse>.Failure(
                Error.Validation("LoanPackage.NoGenerator",
                    "No PDF generator is registered for LoanPackage. Ensure LoanPackageReportGenerator is registered."));

        // Mark previous packages as not-current
        var previousPackages = await db.LoanPdfPackages
            .Where(p => p.ApplicationId == request.ApplicationId && p.IsCurrent)
            .ToListAsync(cancellationToken);
        foreach (var prev in previousPackages)
            prev.IsCurrent = false;

        // DG-LOAN-03: Build a ReportJob so LoanPackageReportGenerator has OrgId + LoanApplicationId.
        // We persist it via IReportServiceDbContext (report.reports table) — the ReportService and
        // LoanService share the same Finance composite DI container.
        var now = DateTime.UtcNow;
        var reportJob = new ReportJob
        {
            OrgId = orgId.Value,
            RequestedBy = currentUser.UserId,
            Title = $"Loan Package — {request.OrgName} — {now:yyyy-MM-dd}",
            ReportType = ReportType.LoanPackage,
            Format = ReportFormat.Pdf,
            LoanApplicationId = request.ApplicationId,
            FinancialYear = null,
            PeriodStart = null,
            PeriodEnd = null,
            Status = ReportJobStatus.Processing,
            StartedAt = now
        };

        reportDb.ReportJobs.Add(reportJob);
        await reportDb.SaveChangesAsync(cancellationToken);

        // Generate the real PDF via LoanPackageReportGenerator
        ReportGenerationResult generationResult;
        try
        {
            generationResult = await generator.GenerateAsync(reportJob, cancellationToken);

            reportJob.Status = ReportJobStatus.Completed;
            reportJob.GcsUri = generationResult.GcsUri;
            reportJob.Sha256HashHex = generationResult.Sha256HashHex;
            reportJob.PageCount = generationResult.PageCount;
            reportJob.CompletedAt = DateTime.UtcNow;
        }
        catch (Exception ex)
        {
            reportJob.Status = ReportJobStatus.Failed;
            reportJob.ErrorMessage = ex.Message;
            reportJob.CompletedAt = DateTime.UtcNow;
            await reportDb.SaveChangesAsync(cancellationToken);

            return Result<GeneratePackageResponse>.Failure(
                Error.Validation("LoanPackage.GenerationFailed",
                    $"PDF generation failed: {ex.Message}"));
        }

        await reportDb.SaveChangesAsync(cancellationToken);

        // Record the loan package in loan.pdf_packages.
        // LoanPdfPackage.Id is auto-generated (BaseEntity protected set — cannot be overridden externally).
        // The report job ID is stored separately for cross-module audit traceability.
        var gcsUri = generationResult.GcsUri;

        var package = new LoanPdfPackage
        {
            ApplicationId = request.ApplicationId,
            GcsUri = gcsUri,
            PagesCount = generationResult.PageCount,
            Sha256Hash = Convert.FromHexString(generationResult.Sha256HashHex),
            GeneratedAt = now,
            GeneratedBy = currentUser.UserId,
            WatermarkText = $"Generated by SnapAccount | {request.OrgName} | {now:yyyy-MM-dd} | Package ID: {reportJob.Id} | Not a CA certification",
            IsCurrent = true
        };

        db.LoanPdfPackages.Add(package);
        await db.SaveChangesAsync(cancellationToken);

        var packageId = package.Id;

        // Build a signed download URL for immediate use
        var objectName = ExtractObjectName(gcsUri);
        var bucketName = Environment.GetEnvironmentVariable(LoanPackagesBucket)
            ?? "snapaccount-loan-packages-dev";
        var signedUrl = await cloudStorage.GetSignedDownloadUrlAsync(bucketName, objectName, TimeSpan.FromHours(1), cancellationToken);

        return new GeneratePackageResponse(
            packageId,
            gcsUri,
            generationResult.PageCount,
            generationResult.Sha256HashHex,
            signedUrl);
    }

    /// <summary>Extracts the object name from a gs:// URI (after the bucket prefix).</summary>
    private static string ExtractObjectName(string gcsUri)
    {
        // gs://bucket-name/object/path → object/path
        if (gcsUri.StartsWith("gs://", StringComparison.OrdinalIgnoreCase))
        {
            var withoutScheme = gcsUri["gs://".Length..];
            var slashIndex = withoutScheme.IndexOf('/');
            return slashIndex >= 0 ? withoutScheme[(slashIndex + 1)..] : withoutScheme;
        }

        // HTTPS storage URL: https://storage.googleapis.com/bucket/object → fall back to last segment
        var uri = new Uri(gcsUri);
        // path is /bucket/object/... — skip the bucket segment (first path segment)
        var segments = uri.AbsolutePath.TrimStart('/').Split('/', 2);
        return segments.Length > 1 ? segments[1] : uri.AbsolutePath.TrimStart('/');
    }
}
